# Generated by Django 3.1.7 on 2021-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaasScPoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrstyle', models.CharField(db_column='qrStyle', max_length=120)),
                ('posterid', models.IntegerField(db_column='posterId')),
                ('title', models.CharField(max_length=120)),
                ('infoid', models.IntegerField(db_column='infoId')),
                ('posterimg', models.CharField(db_column='posterImg', max_length=120)),
                ('createtime', models.IntegerField(db_column='createTime')),
                ('status', models.IntegerField()),
                ('shopcode', models.CharField(db_column='shopCode', max_length=20)),
                ('sellerid', models.IntegerField(db_column='sellerId')),
            ],
            options={
                'db_table': 'saas_sc_poster',
                'managed': False,
            },
        ),
    ]
