# Generated by Django 3.1.7 on 2021-03-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chuser',
            table='ch_user',
        ),
    ]
